### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'hidden'

### ISSUE THREAD

**Issue by clickinfinite** [jackeyGao/request-meta#1]
您好，

感谢您开源这个优秀的项目。不过我安装过程中遇到一些问题，可以帮我debug一下吗？

在linode ubuntu18.04上面运行“python3 server.py”显示错误“TypeError: __init__() got an unexpected keyword argument 'hidden'”

在windows10 pycharm本地运行“python3 server.py”显示错误“ImportError: cannot import name 'get_logger'”

**Comment by jackeyGao** [comment]
我看下你安装的依赖项目 
使用

```
pip list
```

**Comment by clickinfinite** [comment]
> 我看下你安装的依赖项目
> 使用
> 
> ```
> pip list
> ```

谢谢您的回复。
`root@li960-172:~/request-meta# pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
aiofiles (0.4.0)
aniso8601 (7.0.0)
apispec (3.1.1)
apistar (0.7.2)
asn1crypto (0.24.0)
attrs (17.4.0)
Automat (0.6.0)
certifi (2018.1.18)
chardet (3.0.4)
click (6.7)
colorama (0.3.7)
command-not-found (0.3)
configobj (5.0.6)
constantly (15.1.0)
cryptography (2.1.4)
distro-info (0.18ubuntu0.18.04.1)
docopt (0.6.2)
graphene (2.1.8)
graphql-core (2.2.1)
graphql-relay (2.0.1)
graphql-server-core (1.1.3)
h11 (0.9.0)
httplib2 (0.9.2)
httptools (0.0.13)
hyperlink (17.3.1)
idna (2.6)
incremental (16.10.1)
iotop (0.6)
itsdangerous (1.1.0)
Jinja2 (2.10.3)
keyring (10.6.0)
keyrings.alt (3.0)
language-selector (0.1)
MarkupSafe (1.1.1)
marshmallow (3.3.0)
netifaces (0.10.4)
PAM (0.4.2)
parse (1.13.0)
peewee (3.9.5)
pip (9.0.1)
promise (2.3)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
pycrypto (2.6.1)
pygobject (3.26.1)
pyOpenSSL (17.5.0)
pyserial (3.4)
python-apt (1.6.4)
python-debian (0.1.32)
python-multipart (0.0.5)
pyxdg (0.25)
PyYAML (3.12)
requests (2.18.4)
requests-toolbelt (0.9.1)
requests-unixsocket (0.1.5)
responder (1.3.1)
rfc3986 (1.3.2)
Rx (1.6.1)
SecretStorage (2.3.1)
service-identity (16.0.0)
setuptools (39.0.1)
six (1.11.0)
ssh-import-id (5.7)
starlette (0.10.7)
systemd-python (234)
Twisted (17.9.0)
typesystem (0.2.4)
ufw (0.36)
unattended-upgrades (0.1)
urllib3 (1.22)
uvicorn (0.11.1)
uvloop (0.14.0)
websockets (8.1)
wheel (0.30.0)
whitenoise (5.0.1)
zope.interface (4.3.2)`

**Comment by clickinfinite** [comment]
> 我看下你安装的依赖项目
> 使用
> 
> ```
> pip list
> ```
为了更方便您debug，您也可以直接登录我的VPS操作

**Comment by jackeyGao** [comment]
@clickinfinite vps信息 赶紧删了， 别被别人看到了。

**Comment by jackeyGao** [comment]
你能把所有的报错信息给我发下吗？  
```
__init__() got an unexpected keyword argument 'hidden' 
```
我看不到这是哪个模块报出来的。

**Comment by clickinfinite** [comment]
> 你能把所有的报错信息给我发下吗？
> 
> ```
> __init__() got an unexpected keyword argument 'hidden' 
> ```
> 
> 我看不到这是哪个模块报出来的。

您好，VPS信息没什么关系的，这个只是一个测试的VPS，很快就会release。所有的报错信息如下：
`root@li960-172:~/request-meta# python3 server.py
Traceback (most recent call last):
  File "server.py", line 3, in <module>
    import responder
  File "/usr/local/lib/python3.6/dist-packages/responder/__init__.py", line 1, in <module>
    from .core import *
  File "/usr/local/lib/python3.6/dist-packages/responder/core.py", line 1, in <module>
    from .api import API
  File "/usr/local/lib/python3.6/dist-packages/responder/api.py", line 11, in <module>
    import uvicorn
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/__init__.py", line 2, in <module>
    from uvicorn.main import Server, main, run
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/main.py", line 285, in <module>
    use_colors: bool,
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 170, in decorator
    _param_memo(f, OptionClass(param_decls, **attrs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1460, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'hidden'
`

**Comment by jackeyGao** [comment]
你在同步下代码， 我刚更新了两个依赖项目。 

重新安装下依赖项

```
responder==1.3.1
uvicorn==0.7.1
Click==7.0
peewee==3.9.5
```

不要忘了更改 root 密码。

**Comment by clickinfinite** [comment]
> 你在同步下代码， 我刚更新了两个依赖项目。
> 
> 重新安装下依赖项
> 
> ```
> responder==1.3.1
> uvicorn==0.7.1
> Click==7.0
> peewee==3.9.5
> ```
> 
> 不要忘了更改 root 密码。

可以了唉，谢谢您。周末愉快。这个VPS我很快就会删掉的，谢谢提醒。
