### ISSUE TITLE
关于设置HTTPS的疑问

### ISSUE THREAD

**Issue by clickinfinite** [jackeyGao/request-meta#2]
再此感谢JG，安装完成以后可以使用http://ip:5042 访问request-meta，我试用了一下感觉request-meta非常的简洁优雅

不过我google了很久也不知道怎么设置https，因为现在有的webhook已经不支持http协议了，仅支持https协议，网络上关于Responder这个库的资料似乎也不多。

关于怎么修改成443端口、安装SSL证书（比如Let's encrypt)，希望JG大佬能在百忙之中抽空补充一下，稍微指点一下思路就好。

**Comment by jackeyGao** [comment]
建议使用 nginx 做 https 转发， 网上nginx + Let's encrypt教程非常多。  不建议通过程序实现 https

**Comment by clickinfinite** [comment]
> 建议使用 nginx 做 https 转发， 网上nginx + Let's encrypt教程非常多。 不建议通过程序实现 https

谢谢您的回复，我去研究一下。
