### ISSUE TITLE
Suggest to loosen the dependency on responder

### ISSUE THREAD

**Issue by Agnes-U** [jackeyGao/request-meta#5]
Hi, your project request-meta(commit id: 7b9545a9a3a784815989cbc449570fe072091bfa) requires "responder==2.0.7" in its dependency. After analyzing the source code, we found that the following versions of responder can also be suitable, i.e., responder 2.0.6, since all functions that you directly (4 APIs: responder.api.API.template, responder.api.API.route, responder.api.API.__init__, responder.api.API.run) or indirectly (propagate to 16 responder's internal APIs and 13 outsider APIs) used from the package have not been changed in these versions, thus not affecting your usage.

Therefore, we believe that it is quite safe to loose your dependency on responder from "responder==2.0.7" to "responder>=2.0.6,<=2.0.7". This will improve the applicability of request-meta and reduce the possibility of any further dependency conflict with other projects. 

May I pull a request to further loosen the dependency on responder?

By the way, could you please tell us whether such an automatic tool for dependency analysis may be potentially helpful for maintaining dependencies easier during your development?

**Comment by jackeyGao** [comment]
Of course, I look forward to your pr.

**Comment by Agnes-U** [comment]
#6
